import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../services/supabase_service.dart';
import '../home/home_screen.dart';
class RegisterScreen extends StatefulWidget{const RegisterScreen({super.key});@override State<RegisterScreen> createState()=>_RegisterScreenState();}
class _RegisterScreenState extends State<RegisterScreen>{final _form=GlobalKey<FormState>();final _name=TextEditingController();final _email=TextEditingController();final _phone=TextEditingController();final _specialty=TextEditingController();final _bar=TextEditingController();final _password=TextEditingController();bool _loading=false;
@override void dispose(){for(final c in [_name,_email,_phone,_specialty,_bar,_password])c.dispose();super.dispose();}
Future<void> _register()async{if(!_form.currentState!.validate())return;setState(()=>_loading=true);try{final profile={'full_name':_name.text.trim(),'phone':_phone.text.trim(),'specialty':_specialty.text.trim(),'bar_number':_bar.text.trim()};if(SupabaseService.isConfigured){final r=await SupabaseService.signUp(email:_email.text.trim(),password:_password.text,profile:profile);if(r.user==null)throw Exception('تعذر إنشاء الحساب.');if(r.session==null){if(mounted){_show('تم إنشاء الحساب. تحقق من بريدك الإلكتروني ثم سجّل الدخول.');Navigator.pop(context);}return;}}else{final p=await SharedPreferences.getInstance();await p.setString('accountEmail',_email.text.trim());await p.setString('accountPassword',_password.text);await p.setString('userName',_name.text.trim());await p.setString('userEmail',_email.text.trim());await p.setString('userPhone',_phone.text.trim());await p.setString('userSpecialty',_specialty.text.trim());await p.setString('barNumber',_bar.text.trim());await p.setBool('isLoggedIn',true);}if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const HomeScreen()),(_)=>false);}catch(e){if(mounted)_show(e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>_loading=false);}}
void _show(String t)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));
Widget _f(TextEditingController c,String l,IconData i,{bool req=false,TextInputType? type})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(controller:c,keyboardType:type,decoration:InputDecoration(labelText:l,prefixIcon:Icon(i),border:OutlineInputBorder(borderRadius:BorderRadius.circular(12))),validator:req?(v)=>v==null||v.trim().isEmpty?'هذا الحقل مطلوب':null:null));
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('إنشاء حساب محامٍ')),body:Form(key:_form,child:ListView(padding:const EdgeInsets.all(18),children:[_f(_name,'اسم المحامي',Icons.person,req:true),_f(_email,'البريد الإلكتروني',Icons.email,req:true,type:TextInputType.emailAddress),_f(_phone,'رقم الهاتف',Icons.phone,type:TextInputType.phone),_f(_specialty,'التخصص',Icons.gavel),_f(_bar,'رقم النقابة',Icons.badge),_f(_password,'كلمة المرور',Icons.lock,req:true),const SizedBox(height:8),SizedBox(height:52,child:ElevatedButton(onPressed:_loading?null:_register,child:_loading?const CircularProgressIndicator():const Text('إنشاء الحساب')))])));
}
